name: provider_shopper
description: A shopping app sample that uses Provider for state management.

version: 1.0.0+1

environment:
  sdk: '>=2.12.0-259.16.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Import the provider package.
  provider: '>=5.0.0-nullsafety.5 <6.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0

flutter:
  uses-material-design: true

  fonts:
    - family: Corben
      fonts:
        - asset: fonts/Corben/Corben-Bold.ttf
          weight: 700
  assets:
    - images/flower.png
    - images/Эхеверия.png
    - images/Адромискус.png
    - images/Хавортия.png
    - images/Хавортия-preview.png
    - images/Адромискус-preview.png
    - images/Эхеверия-preview.png